# Generated by Django 5.0 on 2023-12-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_upload_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='action',
            field=models.CharField(choices=[('NO_FILTER', 'NO_FILTER'), ('COLORIZED', 'colorized'), ('GRAYSCALE', 'grayscale'), ('BLURRED', 'blurred'), ('BINARY', 'binary'), ('INVERT', 'invert'), ('FACE_DETECTION', 'face_detection'), ('CLASSIFICATION', 'classification'), ('SKETCHED', 'sketched'), ('SHAPE', 'shape'), ('DOCUMENT', 'document')], max_length=50),
        ),
    ]
